### ISSUE TITLE
Parsing impressions

### ISSUE THREAD

**Issue by anelachan** [Data4Democracy/disinfo-campaigns#2]
I noticed that for ~300 records, Impressions is < Clicks. This seems to arise from a parsing error where it's not getting the numbers following the commas for some of the pages. I suspect this comes from this line: https://github.com/Data4Democracy/disinfo-campaigns/blob/master/house-psci-facebook-2018/ad-extract-R/ParseAds.R#L65

**Comment by anelachan** [comment]
This is good to close, right @scottcame ?

**Comment by scottcame** [comment]
Sure is @anelachan ... thanks again for raising it!
