### ISSUE TITLE
Missing CreationTime and EndTime

### ISSUE THREAD

**Issue by j2kao** [Data4Democracy/disinfo-campaigns#6]
Parsing of time fields not working in certain cases -- may be related to redactions in the pdf

Examples:
- `/2017-03/P(1)0006432.pdf`
- `/2017-03/P(1)0006500.pdf`

**Comment by j2kao** [comment]
Also found at: `/2015-06/P(1)0002112.pdf`

**Comment by scottcame** [comment]
I tweaked the regexes for the date/time fields a bit to get us down to six that didn't parse.  I checked these three explicitly and they are now valid. Commit 5a3c026
